### ISSUE TITLE
기획 정하기

### ISSUE THREAD

**Issue by hwiba** [Link413/KROMBACHER#1]
2015년 12월 19일까지 아이디어를 모집하여 20일 경에 결정을 목표한다.
## 현재까지 나와있는 아이디어.
1. 류성현
   - trello와 유사하되 shallow copy 기반으로(다른 리스트로 카드를 복사하면, 다른데서 수정해도 반영되게)
   - symbolic link(?)
   - schedule 연동이 되서 달력에 표시
   - 즉, [달력뷰 + 카드 리스트 + 심볼릭 링크]
2. 이성천
   - github는 너무 개발자 친화적. 비 개발자도 git의 장점을 누릴 수 있는 서비스가 있으면 좋겠다.
   - 그림이든 글이든 되게

**추가 아이디어는 코멘트로.**

**Comment by boorownie** [comment]
1번 아이디어에 가지를 친 생각인데
Opne API 형태로 제공한다는 가정을 하면 서드파티 서비스를 만들 수 있도록 확장할 수 있게 만들면 좋겠음.
ex 1) 가계부 서드파티 서비스
- 카드의 포맷을 가계부로 지정을 하면 가계부포맷에 맞게 작성해야한다.
- 이렇게 작성된 카드들을 한 리스트에 담아둔다.
- 해당 리스트의 정보를 api 형태로 제공하면 서드파티앱에서 해당 정보를 받아와서 파싱하여 앱 형태로 서비스를 제공 할 수 있다.

ex 2) 주소록 (쓸모는 없지만..ㅋ)

**Comment by hwiba** [comment]
ex 1)은 유의미 해보임. 
ex 2)의 주소록이 의미하는 내용을 잘 모르겠는데 정확히 어떤 기능?

**Comment by hwiba** [comment]
github와 apple 캘린더를 연동하는 건 어떨까.
마일스톤을 달력으로.
이슈를 미리알림으로.

**Comment by hwiba** [comment]
@probitanima11 의 기획안으로 결정.
