### ISSUE TITLE
모바일 기본 세팅 시작하기

### ISSUE THREAD

**Issue by hwiba** [Link413/KROMBACHER#12]
레포지터리에 첫 커밋하기

**Comment by HelloMocca** [comment]
모바일 프로젝트가 초기화 된 이후 이 이슈를 Close 하세요.
이후 각 플랫폼별 이슈는 해당 레포에서 이루어지도록 합시다.

**Comment by hwiba** [comment]
@HelloMocca 각 플랫폼 별 이슈가 각 레포지터리 별로 따로 운영되면 관심을 가지고 살펴보기가 어렵지 않을지..?

**Comment by ybin0823** [comment]
@Link413/krombacher-ios  권한 가지는 crombacher-ios team 개설후,  @ybin0823 과 @miyaeyo 권한 설정
최초 README.md 파일과 프로젝트 push

**Comment by HelloMocca** [comment]
모여있다고 특별하게 관심이 늘거나 줄지는 않을 것 같고 관리상 분리하는게 맞을것 같음.
