### ISSUE TITLE
Commit Convention

### ISSUE THREAD

**Issue by ybin0823** [Link413/KROMBACHER#13]
부서에서는 Commit을 한글로 쓰지만,
많은 개발자는 영어를 권장하기도 함.

한글 vs 영어

**Comment by HelloMocca** [comment]
비공개 프로젝트니까 한글을 쓰는게 적당할듯

영어를 쓰면 좋긴한데 메세지를 적을때 너무 오래걸림 ㅋㅋ

**Comment by hwiba** [comment]
영어를 쓰면 좋은 이유가 외국계와의 히스토리를 통한 소통 + 해외로 진출할 때를 대비해서 미리 연습함 정도의 의미가 아닐까 싶은데, 당장 이 스터디 프로젝트가 몸에 익지 않은 상태에서 영어 커밋은 부담을 늘릴 수 있을 듯. 천천히 적용해가면 어떨까?

**Comment by miyaeyo** [comment]
간지가 안납니다

**Comment by hwiba** [comment]
@miyaeyo 그래서 영어입니까 한국어입니까

**Comment by ybin0823** [comment]
간지는 영어지만, 일단은 한글로 시작하는게 좋을 듯요.
추후에 rebase라는 기능을 공부 잘하면 commit을 싹 영어로 바꾸는 작업도 할 수 있으니까요.
