### ISSUE TITLE
팀 메신저를 무엇으로 할 것인가?

### ISSUE THREAD

**Issue by hwiba** [Link413/KROMBACHER#16]
현재 K 모 사의 상용 서비스를 사용하고 있는데

이것이 각 구성원들의 환경을 살펴보았을 때 적절하지 않다는 논의가 있었다.

slack이나 기타 다른 도구에 대해 논의해보고, 충분한 이점이 있다면 교체하자.

**Comment by alpha2015** [comment]
텔레그램은 어떤가요??

**Comment by hwiba** [comment]
텔레그램은 봇 api가 공개되어 있어서 서버 모니터링 등에 쓰기 좋기는 한 듯.

**Comment by miyaeyo** [comment]
그럼 텔레그램 쓰나여??

**Comment by miyaeyo** [comment]
슬랙으로 결정
