### ISSUE TITLE
브랜치 전략 결정하기

### ISSUE THREAD

**Issue by hwiba** [Link413/KROMBACHER#2]
나는 브랜치 전략에 대한 경험이 적은데, 다들 어떻게 하고 있는지?

게중 우리가 하기에 적합한 것은 어떤 것인지 논의할 수 있다면 좋겠다.

**Comment by ybin0823** [comment]
http://dogfeet.github.io/articles/2011/a-successful-git-branching-model.html

git flow 모델을 우리팀에서 사용하고 있고. 현업에서도 많ㅇ 쓰는듯

**Comment by alpha2015** [comment]
우리팀의 경우
브렌치를 크게 2개 +깃플로우를 사용
예를 들어 마스터(리얼서버배포용) / 디벨롭(개발용) / 깃플로우-피쳐(개인 새기능 구현시) / 깃플로우-핫픽스(긴급오류수절) 
깃플오유 경우 기능이나 버그가 개선되면 디벨롭에 머지

**Comment by hwiba** [comment]
[http://blog.weirdx.io/git-flow-github-flow-gitlab-flow/](http://blog.weirdx.io/git-flow-github-flow-gitlab-flow/) 이런 문서가 있는데 참고해보자.
