### ISSUE TITLE
다음 오프라인 스터디 주제와 일정

### ISSUE THREAD

**Issue by hwiba** [Link413/KROMBACHER#4]
크게
- swift
- spring boot
- jpa
- 엘라스틱 서치

정도일 것 같지만 기본적으로 자유 주제인데,
1. 꼭 전원이 모여야만 스터디가 성립되는 것은 아니므로 개별적으로 모이더라도 모였다는 사실 정도는 위키에 적어두면 어떨까?
2. 모임 일정과 멤버는 어떻게 결정하지? 현 Link413 멤버에서 추가로 더 멤버를 영입하는 건에 대해서는 어떻게들 생각? 프로젝트는 같이 하지 않더라도 스터디를 모이는 것은 가능하지 않을까? 프로젝트도 같이 해주면 더 좋고.

**Comment by boorownie** [comment]
월 1회 정기오프라인 모임을 건의
이것도 정기오프라인모임 마스터를 둬서 한사람씩 주체하고 다음사람을 지정(or 자원)하는 방식으로 진행되면 좋을것 같음

**Comment by hwiba** [comment]
월 1회의 정기 오프라인 모임으로 주말 오전 시간을 선택하는 것은 어떨까? 평일 퇴근 후라는 시간도 좋기는 하지만 한달에 한번 모이는 오프라인 모임인데 회의에 대한 집중력이 떨어지지 않을까하는 우려가 있다.

**Comment by alpha2015** [comment]
정기 월1회 오프라인도 좋고 저번에 언급된
같이 모여 스터디 그자리에서 공부하고
바로 토론도 좋아보임 물론 이방식으로 진행하면 온라인으로 스터디시 에로사항이 많아 보임

**Comment by hwiba** [comment]
@alpha2015 오프라인에서 있었던 토의는 대강 큰 줄기만이라도 기록해서 위키에 올릴 필요가 있을 듯.
