### ISSUE TITLE
어떻게 의사소통할 것인가?

### ISSUE THREAD

**Issue by hwiba** [Link413/KROMBACHER#5]
기본적으로 이슈를 통해서 의사소통하는 것이 나중에 확인하기에 좋기는 하지만 즉시성이 떨어진다는 단점이 있다.

때문에 자잘한 관련 대화를 나누기는 좋지 않는데 메신저 형태의 서비스로 어떤 것을 사용하면 좋겠다.

카카오톡, 라인, 텔레그램 등 여러가지 메신저가 있지만 slack 등도 고려해볼만 하다.

이에 대해 논의해보자.

**Comment by hwiba** [comment]
- 나는 하루에 한번 정도나 이틀에 한번 정도 시간 날때마다 깃허브 이슈에 들어가서 확인하는 방법도 괜찮다고 생각함.
- 병렬적으로 여러가지 주제에 대해 논하기도 괜찮고 즉시성이 떨어지기는 하지만 대신 한가지 주제에 대해 천천히 생각해보기 괜찮은 듯.

**Comment by boorownie** [comment]
슬랙을 이용한 [일일회의](https://github.com/Link413/KROMBACHER/wiki/%EC%9D%BC%EC%9D%BC%ED%9A%8C%EC%9D%98) 추천

**Comment by hwiba** [comment]
@probitanima11 일일회의의 아이디어가 좋다고 생각하는데 첫 번째 스크럼 마스터가 되어 볼 생각이 있는지?

**Comment by hwiba** [comment]
일일회의에 적합한 시간은 어떻게 선정해야할까?

**Comment by alpha2015** [comment]
하루 10-15분 시간 정해서 슬랙을 통해 의사 결정은 어떱니까

**Comment by hwiba** [comment]
평일 중 하루 10분의 일일 회의에 대한 논의가 있었다. 이에 대해 각자 적절한 시간을 찾기 위한 투표 중.
투표 결과는 @probitanima11 가 2015년 12월 22일 중 확인하여 전파할 것.

해당 이슈는 [여기](https://github.com/Link413/KROMBACHER/issues/9)
