### ISSUE TITLE
어떻게  ios와 server의 repository를 관리할 것인가?

### ISSUE THREAD

**Issue by hwiba** [Link413/KROMBACHER#6]
- LInk413에 새 repository를 파서 ios를 분리해야하는지
- 아니면 디렉터리를 나눠서 ios 디렉터리를 둘 것인지
- 혹은 또다른 방법으로는 어떤 것이 있을지

**Comment by hwiba** [comment]
브랜치를 나누는 것도 하나의 전략일 수 있겠다.

**Comment by ybin0823** [comment]
현재 이곳 repository는 코드외에 전반적인 이슈와 wiki가 있어서.
krombacher-Server,  -iOS
이런식으로 link413아래에 별도의 리파지토리가 있는게 낫지 않으까

**Comment by ybin0823** [comment]
서버나 클라이언트에서 발생하는 이슈는 각 리파지토리에 남기는 것으로.
사내 BTS같은 서비스가 없으니 Github의 issue를 적극 활용하는게 좋을듯

**Comment by alpha2015** [comment]
백앤드 클라를 같은 레포지에 브랜치로 따게 되면 
추후 백앤드나 서버 새 피쳐나 디벨롭 브랜치를 두게 되면 많은 혼란이 야기 될것 같으므로
link413내에서 새 레포지를 따는게 좋다고 생각합니다

**Comment by hwiba** [comment]
결과
- KROMBACHER
- KROMBACHER-IOS
- KROMBACHER-ANDROID

이렇게 3개 Repository로 나누게 되었습니다.
