### ISSUE TITLE
test 서버 둘 것인가? 둔다면 어디에 둘 것인가?

### ISSUE THREAD

**Issue by hwiba** [Link413/KROMBACHER#7]
CI를 비롯한 인프라에 관심이 있는 인원이 있는만큼,
 비록 서비스를 런칭하는 것은(가능하다면) 수 개월 이상 뒤가 되겠지만 테스트 서버가 있는 것이 좋지 않을까?

만약 테스트 서버를 마련하는 것에 동의한다면, 어떤 서버를 사용해야할까?
- AWS
- MS 애저
- 구글 앱엔진
- 기타 등등

**Comment by alpha2015** [comment]
테스트 서버를 굳이 리얼 1차 배포전 둘 필요가 있을까? 베타서비스 시작하기 바로 전쯤 구성하면 될것 같기도 하다는 생각이 듭니다 
물론 이건 개인적인 의견

**Comment by hwiba** [comment]
테스트 서버를 두고자 하는 것은
1. 인프라 세팅(CI 툴 등)을 공부하고자 하는 @probitanima11 이 있어서,
2. 모바일 개발 파트가 굳이 백엔드 환경 설정을 해야하는 피곤함을 줄이고자 하는 목적이 있는데
너무 일찍 나가는 것이 아닌가 하는 생각이 드는 것도 사실.

@probitanima11 , @ybin0823 은 어떻게 생각하는지?

**Comment by hwiba** [comment]
@alpha2015 sonarqube를 위해서도 테스트 서버가 필요하지 않을까?

**Comment by alpha2015** [comment]
일단 서버한대에서 개발하거 인프라 구축하고 테스트 해본다음 릴리즈전 이 서버를 테스트로 가고 실서버를 그때 새로 구매하는것 어떻게 생각함

**Comment by ybin0823** [comment]
@alpha2015  알파형 의견에 동감. 굳이 처음부터 테스트서버/ 실서버 구분할 필요없이. 서버 하나에다가 작업 다하고 배포를 할 떄, 그 서버를 테스트로 쓰고 실서버는 새로 구축하면 될 듯

**Comment by ybin0823** [comment]
@hwiba 서버가 분리되면 현업에서는 빌드-배포할 때 scheme라는 것을 정의해놔서 그것만 바꿔가면서 빌드를 해서. 추후에 scheme 사용법도 익힐 수 있고 좋을듯

**Comment by hwiba** [comment]
@alpha2015 , @ybin0823 의 의견을 조합해보면 한대의 테스트 전용 서버를 가지는 것이 맞는 듯 한데,
서버를 어디에 구축할 것인지가 문제다.
기술적으로는 소나큐브나 젠킨스 등을 설치할 텐데 그 정도는 어떤 클라우드 플랫폼에서도 별 무리가 없을 것.

그럼 남는 건 클라우드 그 자체를 학습하는 용도가 있겠다.
여기에 대해서 별도로 선호하는 클라우드가 있는지? 혹은 이에 대해 전담해서 클라우스 서버 세팅을 시도해보고자 하는 인원이 있는지?

**Comment by hwiba** [comment]
Test 서버를 하나 두는 것으로 하여, 어느 서버를 쓸 지는 다음 마일스톤으로.
