### ISSUE TITLE
일일 회의 시간에 대한 이슈

### ISSUE THREAD

**Issue by hwiba** [Link413/KROMBACHER#9]
@probitanima11 : 투표 결과를 확인하고 전파할 것.

정말 매일인지 의논할 것.

**Comment by ybin0823** [comment]
나는 매일 조금씩 하는거는 좀 별로 같음.. 현업에서도 주간회의로 1주일에 딱 한번 하는데
개인적으로는 1주일에 한번 회의하면서 '지난주에는 이런 이슈가 있어서 이런 부분을 처리했다. 혹은 이런 것을 학습했다. 이번주는 이런이런 기능을 하겠다.'  이정도로만 하는게 낫지 않을까?

**Comment by hwiba** [comment]
주간 이슈로 운영하자는 의견이 있었다.
매일 하는 것보다 탄력적이기는 하지만 그만큼 현재 이슈 상황에 대한 캐치가 늦을 수 있는게 단점일텐데,
슬랙 등의 연동을 통해 이슈 상황을 빠르게 자동 전파하거나 수동으로 메신저에 올리는 방법을 고려해보자.
